shortlink/urls.py
from django.urls import path
from django.urls.conf import include
from . import views
from . import api_views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()
#router.register(r'users', api_views.UserViewSet)
#router.register(r'groups', api_views.GroupViewSet)
router.register(r'links', api_views.LinkViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/api-token-auth/', obtain_auth_token),
    path('', views.HomeView.as_view(), name='main'),
    path('account/', views.ProfileView.as_view(), name='profile'),
    path('account/sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('account/sign-in/', views.SignInView.as_view(), name='sign-in'),
    path('account/sign-out/', views.SignOutView.as_view(), name='sign-out'),
    path('account/links/', views.LinksView.as_view(), name='links'),
    path('account/links/create', views.LinkCreateView.as_view(), name='create-link'),
    path('<str:link>/', views.RedirectToView.as_view(), name='redirect'),
    path('<str:link>/delete/', views.DeleteRedirectView.as_view(), name='redirect-delete')
]

shortlink/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date
import shortuuid as shortid
from django.db import IntegrityError

# Create your models here.

class Link(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    link_to = models.URLField()
    link_from = models.CharField(max_length=10, unique=True)
    counter = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "[%s]:%s -> %s" % (self.user.username, self.link_from, self.link_to[:30])

    def save(self, *args, **kwargs):
        attempt = 0
        if self.link_from != '':
            super().save(*args, **kwargs)
            return
        while True:
            try:
                self.link_from = shortid.uuid()[:8]
                super().save(*args, **kwargs)
                return 
            except IntegrityError as E:
                attempt = attempt + 1
                if attempt == 3:
                    raise E  

class Profile(models.Model):
    GENDERS = (
        ('m', 'Male'),
        ('f', 'Female')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    gender = models.CharField(max_length=1, choices=GENDERS, default='m')
    birth_date = models.DateField(default=date.today)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

shortlink/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        label = "Username",
        max_length = 150,
        required = True,
        help_text="150 characters or fewer. Letters, digits and @/./+/-/_ only"
        )
    email = forms.EmailField(
        label = "Email",
        required = True
    )
    gender = forms.ChoiceField(
        label = "Genger",
        choices=Profile.GENDERS
        )
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={
            'type':'date',
        }))
    class Meta:
        model = User
        fields = ('username', 'email', 'birth_date','gender' ,'password1', 'password2', )

shortlink/views.py
from django.views.generic.edit import FormView, DeleteView, CreateView
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import ListView
from .forms import SignUpForm
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, authenticate, views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Link
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.db.models import F

class LinkCreateView(LoginRequiredMixin,CreateView):
    login_url = reverse_lazy('sign-in')
    template_name = 'shortlink/create-link.html'
    model = Link
    fields = ['link_to']
    title = 'create-link'


    def form_valid(self, form):
        form.instance.user = self.request.user
        link = form.save()
        link.save()
        context = self.get_context_data(form=form)
        context['new_link'] = link.link_from
        return self.render_to_response(context)
            

class LinksView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('sign-in')
    success_url = reverse_lazy('link-list')
    template_name = 'shortlink/links.html'
    title = 'links'
    paginate_by = 5

    def get_queryset(self):
        queryset = Link.objects.filter(user = self.request.user).order_by('-create_date')
        return queryset

class DeleteRedirectView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('sign-in')
    model = Link
    success_url = reverse_lazy('links')
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(self.success_url)

    def delete(self, request, *args, **kwargs):
        self.object = get_object_or_404(Link, link_from=kwargs['link'])
        if request.user != self.object.user:
            raise PermissionDenied 
        self.object.delete()
        return HttpResponseRedirect(self.success_url)

class RedirectToView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        link = get_object_or_404(Link, link_from=kwargs['link'])
        link.counter = F("counter") + 1
        link.save(update_fields=["counter"])
        return link.link_to

class HomeView(TemplateView):
    template_name = 'shortlink/home.html'
    title = 'home'



class ProfileView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('sign-in')
    template_name = 'shortlink/profile.html'
    title = 'profile'


class SignUpView(FormView):
    template_name = 'shortlink/sign-up.html'
    form_class = SignUpForm
    success_url = reverse_lazy('links')
    title = 'sign-up'
    
    def form_valid(self, form):
        user = form.save()
        user.refresh_from_db()
        user.profile.birth_date = form.cleaned_data.get('birth_date')
        user.profile.gender = form.cleaned_data.get('gender')
        user.save()
        login(self.request, user)
        return super().form_valid(form)

class SignInView(auth_views.LoginView):
    template_name = 'shortlink/sign-in.html'
    success_url = reverse_lazy('profile')
    title = 'sign-in'

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or self.success_url

class SignOutView(auth_views.LogoutView):
    next_page = '/'
    

shortlink/templates/shortlink/base.html
<!DOCTYPE html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
</head>
<body>
    {% include 'shortlink/navbar.html' %}
    {% block content %}{% endblock %}
</body>

shortlink/templates/shortlink/create-link.html
{% extends "shortlink/base.html" %}

{% block title %}Home{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .asteriskField {
        display: none;
    }
</style>
<div class="container" style="padding-top: 1.5rem;">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn btn-primary btn-lg" style="margin-top:1em;">Create shortlink</button>
        {% if new_link %}
        <script>
            window.history.pushState(null, "");
        </script>
        <div class="alert alert-success" role="alert" style="margin-top: .5rem;">
            Link was created successfully:
             <a href="{{ request.scheme }}://{{ request.get_host }}{% url 'redirect' link=new_link %}" 
             class="alert-link">{{ request.scheme }}://{{ request.get_host }}{% url 'redirect' link=new_link %}</a>.
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

shortlink/templates/shortlink/home.html
{% extends "shortlink/base.html" %}

{% block title %}Home{% endblock %}
{% load static %}
{% block content %}
<div class="text-center">
    <img src="{% static 'shortlink/logo.png' %}" class="rounded" alt="Logo" style="width:300px;
    height:auto;">
    <p class="lead">Make your link more convenient</p>
</div>
{% endblock %}

shortlink/templates/shortlink/links.html
{% extends "shortlink/base.html" %}

{% block title %}Links{% endblock %}
{% load static %}
{% block content %}
<link href="{% static 'shortlink/style.css' %}" rel="stylesheet">

<div class="container" style="margin-top:0.5rem;">
  <a class="btn btn-outline-primary float-end" href="{% url 'create-link' %}" role="button">Create new shortlink</a>
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Link to</th>
        <th scope="col">Link from</th>
        <th scope="col">Creation date</th>
        <th scope="col">Click count</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
{% for links in object_list %}
<tr>
    <th scope="row">{{ page_obj.start_index|add:forloop.counter0 }}</th>
    <td class="dont-break-out"><a href="{{ links.link_to }}" target="_blank" rel="nofollow noopener">{{ links.link_to}}</a></td>
    <td ><a href="{{ request.scheme }}://{{ request.get_host }}{% url 'redirect' link=links.link_from %}" rel="nofollow noopener">
        {{ request.scheme }}://{{ request.get_host }}{% url 'redirect' link=links.link_from %}</td>
    <td>{{ links.create_date }}</td>
    <td>{{ links.counter}}</td>
    <td>
        <form method="POST" action="{% url 'redirect-delete' link=links.link_from %}"> 
            {% csrf_token %}<input type="submit" class="btn btn-outline-danger"  value="Delete">
        </form>
</tr>
{% empty %}
        <td>
            No link created yet. 
        </td>
{% endfor %}
    </tbody>
    </table>
    {% if page_obj.has_previous or page_obj.has_next %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item {% if not page_obj.has_previous %}disabled {% endif %}">
            <a class="page-link" 
            {% if page_obj.has_previous %}
            href="?page={{ page_obj.previous_page_number }}"
            {% endif %}
             tabindex="-1">Previous</a>
          </li>
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-1' }}">{{ page_obj.number|add:"-1" }}</a></li>
          {% endif %}
          <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'1' }}">{{ page_obj.number|add:"1" }}</a></li>
          {% endif %}
          <li class="page-item {% if not page_obj.has_next %}disabled {% endif %}">
            <a class="page-link" 
            {% if page_obj.has_next %}
            href="?page={{ page_obj.next_page_number }}"
            {% endif %}
            >Next</a>
          </li>
        </ul>
      </nav>
      {% endif %}
</div>

{% endblock %}

shortlink/templates/shortlink/navbar.html
<nav class="navbar navbar-light navbar-expand-sm navbar" style="background-color: #e3f2fd; margin-bottom: 0.5 rem;" >
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main' %}">ShortLink</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav ">
                <a class="nav-link {% if view.title == 'home' %}active{% endif %}" href="{% url 'main' %}">Home</a>
                {% if user.is_authenticated %}
                <a class="nav-link {% if view.title == 'profile' %}active{% endif %}" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link {% if view.title == 'chat' %}active{% endif %}" href="{% url 'chat' %}">Chat</a>
                <a class="nav-link {% if view.title == 'links' %}active{% endif %}" href="{% url 'links' %}">Links</a>
                <a class="nav-link" href="{% url 'sign-out' %}">Sign out</a>
                {% else %}
                <a class="nav-link {% if view.title == 'sign-in' %}active{% endif %}" href="{% url 'sign-in' %}">Sign in</a>
                <a class="nav-link {% if view.title == 'sign-up' %}active{% endif %}" href="{% url 'sign-up' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

shortlink/templates/shortlink/profile.html
{% extends "shortlink/base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container" style="margin-top:0.5rem;">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Profile information</h4>
            <table class="table">
            <tr>
                <td>Username</td>
                <td>{{ view.request.user.username }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ view.request.user.email }}</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>{{ view.request.user.profile.get_gender_display }}</td>
            </tr>
            <tr>
                <td>Birth date</td>
                <td>{{ view.request.user.profile.birth_date }}</td>
            </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

shortlink/templates/shortlink/sign-in.html
{% extends "shortlink/base.html" %}

{% block title %}Sign in{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .asteriskField {
        display: none;
    }
</style>

<div class="container" style="padding-top: 1.5rem;">
<form method="post">
    {% csrf_token %}
    <h3 class ="mx-auto text-center">Sign in</h3>
    <div class="row ustify-content-md-center"> 
            {% if view.get_redirect_url %}
        <p class ="text-center alert alert-info">You must sign in to continue.</p>
            {% endif %}
        {{ form|crispy }}
    <div class="col-8 mx-auto text-center">
        <button type="submit" class="btn btn-primary btn-lg" style="margin-top:1em;">Sign in</button>
        <p style="padding-top: 1rem;">Don't have an account yet? <a href="{% url 'sign-up' %}">Sign Up</a></p>
    </div>
    </div>
</form>
</div>
{% endblock %}

shortlink/templates/shortlink/sign-up.html
{% extends "shortlink/base.html" %}

{% block title %}Sign up {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
.asteriskField {
    display: none;
}
</style>

<div class="container" >
<form method="post">
    {% csrf_token %}
    <h3 class ="mx-auto text-center">Sign up</h4>
    <div class="row mx-auto">
        <div class="col-sm-6">
            {{ form.username|as_crispy_field }}
        </div>
        <div class="col-sm-6">
            {{ form.email|as_crispy_field }}
        </div>
        <div class="col-sm-6">
            {{ form.birth_date|as_crispy_field }}
        </div>
        <div class="col-sm-6">
            {{ form.gender|as_crispy_field }}
        </div>
        <div class="col-sm-6">
            {{ form.password1|as_crispy_field }}
        </div>
        <div class="col-sm-6">
            {{ form.password2|as_crispy_field }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary btn-lg" style="width: 100%!important; margin:0.5rem">Sign up</button>
    
</form>
</div>
{% endblock %}